# Launch a ros master with the controller manager and associated services
version: "3.8"

services:
  # base container -- will simply exit once brought up
  # we can run commands via this container for running experiments, etc.
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile
    <<: &base
      image: ivalab/gknet:latest
      network_mode: host
      shm_size: 2gb
      volumes:
        - ./:/catkin_ws/src/app
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ~/.Xauthority:/root/.Xauthority
      environment:
        DISPLAY: $DISPLAY
        QT_X11_NO_MITSHM: 1
  gpu:
    <<: *base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
